(defconst +asm-abbrev-table-register+
  '(("eax" . "%eax")
    ("ax" . "%ax")
    ("ah" . "%ah")
    ("al" . "%al")
    ("ebx" . "%ebx")
    ("bx" . "%bx")
    ("bh" . "%bh")
    ("bl" . "%bl")
    ("ecx" . "%ecx")
    ("cx" . "%cx")
    ("ch" . "%ch")
    ("cl" . "%cl")
    ("edx" . "%edx")
    ("dx" . "%dx")
    ("dh" . "%dh")
    ("dl" . "%dl")
    ("edi" . "%edi")
    ("esi" . "%esi")
    ("ebp" . "%ebp")
    ("esp" . "%esp")))


(define-abbrev-table 'asm-mode-abbrev-table '())
(mapcar #'(lambda (abbrev-replace)
	    (define-abbrev asm-mode-abbrev-table (car abbrev-replace) (cdr abbrev-replace) nil :system t))
	+asm-abbrev-table-register+)
(abbrev-mode t)
(setq local-abbrev-table asm-mode-abbrev-table)

(provide 'foo-asm-mode)